In [121]:
import os 
from glob import glob
import pandas as pd
from functools import reduce
from xml.etree import ElementTree as et

In [122]:
# load all xml files and store in a list 
xmlfiles = glob('./data_images/*.xml')

#data cleaning replace //with /
replace_text = lambda x: x.replace('\\','/')
xmlfiles = list(map(replace_text, xmlfiles))

In [123]:
xmlfiles

['./data_images/00.xml',
 './data_images/01.xml',
 './data_images/02.xml',
 './data_images/03.xml',
 './data_images/04.xml',
 './data_images/06.xml',
 './data_images/07.xml',
 './data_images/08.xml',
 './data_images/09.xml',
 './data_images/10.xml',
 './data_images/11.xml',
 './data_images/12.xml',
 './data_images/13.xml',
 './data_images/15.xml',
 './data_images/16.xml',
 './data_images/17.xml',
 './data_images/18.xml',
 './data_images/19.xml',
 './data_images/20.xml',
 './data_images/21.xml',
 './data_images/23.xml',
 './data_images/24.xml',
 './data_images/25.xml',
 './data_images/26.xml',
 './data_images/27.xml',
 './data_images/28.xml',
 './data_images/29.xml',
 './data_images/30.xml',
 './data_images/31.xml',
 './data_images/32.xml',
 './data_images/33.xml',
 './data_images/34.xml',
 './data_images/35.xml',
 './data_images/36.xml',
 './data_images/37.xml',
 './data_images/38.xml',
 './data_images/40.xml',
 './data_images/41.xml',
 './data_images/42.xml',
 './data_images/43.xml',
 './data_images/44.xml']

In [124]:
# step-2 read xml files 
#from each xml file we need to extract 
# filename, size(width, height), object(name, xmin, xmax, ymin, ymax )
def extract_text(filename):
    tree = et.parse(filename)
    root = tree.getroot()
    #extract filename
    image_name = root.find('filename').text
    print('Imagename:', image_name)
    #width and height of the image 
    width = root.find('size').find('width').text
    height = root.find('size').find('height').text
    objs = root.findall('object')
    parser = []
    for obj in objs:
        name = obj.find('name').text
        bndbox = obj.find('bndbox')
        xmin = bndbox.find('xmin').text
        xmax = bndbox.find('xmax').text
        ymin = bndbox.find('ymin').text
        ymax = bndbox.find('ymax').text
        parser.append([image_name, width, height, name, xmin, xmax, ymin, ymax])
    
    return parser

In [125]:
parser_all = list(map(extract_text, xmlfiles))

Imagename: 00.jpg
Imagename: 01.jpg
Imagename: 02.jpg
Imagename: 03.jpg
Imagename: 04.jpg
Imagename: 06.jpg
Imagename: 07.jpg
Imagename: 08.jpg
Imagename: 09.jpg
Imagename: 10.jpg
Imagename: 11.jpg
Imagename: 12.jpg
Imagename: 13.jpg
Imagename: 15.jpg
Imagename: 16.jpg
Imagename: 17.jpg
Imagename: 18.jpg
Imagename: 19.jpg
Imagename: 20.jpg
Imagename: 21.jpg
Imagename: 23.jpg
Imagename: 24.jpg
Imagename: 25.jpg
Imagename: 26.jpg
Imagename: 27.jpg
Imagename: 28.jpg
Imagename: 29.jpg
Imagename: 30.jpg
Imagename: 31.jpg
Imagename: 32.jpg
Imagename: 33.jpg
Imagename: 34.jpg
Imagename: 35.jpg
Imagename: 36.jpg
Imagename: 37.jpg
Imagename: 38.jpg
Imagename: 40.jpg
Imagename: 41.jpg
Imagename: 07.jpg
Imagename: 08.jpg
Imagename: 09.jpg

In [126]:

parser_all

[[['00.jpg', '5016', '2822', 'Car', '234', '1923', '1384', '1863'],
  ['00.jpg', '5016', '2822', 'Car', '1650', '3076', '1289', '1794'],
  ['00.jpg', '5016', '2822', 'Car', '3025', '4593', '977', '2089']],
 [['01.jpg', '1366', '768', 'Car', '28', '531', '551', '768'],
  ['01.jpg', '1366', '768', 'Car', '545', '905', '515', '667'],
  ['01.jpg', '1366', '768', 'Car', '961', '1247', '498', '604'],
  ['01.jpg', '1366', '768', 'Car', '1010', '1335', '612', '767']],
 [['02.jpg', '4128', '3096', 'Car', '1797', '2693', '2214', '2704'],
  ['02.jpg', '4128', '3096', 'Car', '497', '1188', '2076', '2481'],
  ['02.jpg', '4128', '3096', 'Car', '893', '1559', '1914', '2266'],
  ['02.jpg', '4128', '3096', 'Car', '183', '712', '1733', '1990'],
  ['02.jpg', '4128', '3096', 'Car', '245', '707', '1609', '1800'],
  ['02.jpg', '4128', '3096', 'Car', '1116', '1778', '1557', '1852'],
  ['02.jpg', '4128', '3096', 'Car', '1816', '2464', '1595', '1833'],
  ['02.jpg', '4128', '3096', 'Car', '873', '2012', '2757', '3096'],
  ['02.jpg', '4128', '3096', 'Car', '2126', '2926', '1871', '2257'],
  ['02.jpg', '4128', '3096', 'Car', '2940', '3893', '2057', '2504'],
  ['02.jpg', '4128', '3096', 'Car', '16', '402', '1438', '1604'],
  ['02.jpg', '4128', '3096', 'Car', '793', '1278', '1328', '1533'],
  ['02.jpg', '4128', '3096', 'Car', '1426', '1821', '1233', '1447'],
  ['02.jpg', '4128', '3096', 'Car', '2212', '2493', '1347', '1528'],
  ['02.jpg', '4128', '3096', 'Car', '2526', '2826', '1342', '1581'],
  ['02.jpg', '4128', '3096', 'Car', '2673', '2950', '1504', '1738'],
  ['02.jpg', '4128', '3096', 'Car', '2578', '2845', '1190', '1352'],
  ['02.jpg', '4128', '3096', 'Car', '935', '1259', '1209', '1333'],
  ['02.jpg', '4128', '3096', 'Car', '2731', '2916', '1114', '1242'],
  ['02.jpg', '4128', '3096', 'Car', '3273', '3754', '1566', '1861']],
 [['03.jpg', '5088', '3253', 'Taxi', '1649', '2091', '2479', '2910'],
  ['03.jpg', '5088', '3253', 'Taxi', '2038', '2301', '2584', '2837'],
  ['03.jpg', '5088', '3253', 'Taxi', '2291', '2565', '2516', '2826'],
  ['03.jpg', '5088', '3253', 'Car', '2695', '2897', '2565', '2753'],
  ['03.jpg', '5088', '3253', 'Ambulance', '2882', '3057', '2510', '2710'],
  ['03.jpg', '5088', '3253', 'Bus', '2679', '2766', '2449', '2500'],
  ['03.jpg', '5088', '3253', 'Car', '3659', '4114', '2504', '2929']],
 [['04.jpg', '1366', '768', 'Car', '631', '879', '392', '723'],
  ['04.jpg', '1366', '768', 'Car', '339', '573', '294', '541'],
  ['04.jpg', '1366', '768', 'Car', '113', '345', '212', '398'],
  ['04.jpg', '1366', '768', 'Car', '1', '306', '364', '757'],
  ['04.jpg', '1366', '768', 'Car', '177', '477', '600', '768'],
  ['04.jpg', '1366', '768', 'Car', '939', '1177', '270', '503'],
  ['04.jpg', '1366', '768', 'Car', '432', '603', '122', '283'],
  ['04.jpg', '1366', '768', 'Car', '234', '424', '62', '233'],
  ['04.jpg', '1366', '768', 'Car', '913', '1080', '93', '244'],
  ['04.jpg', '1366', '768', 'Car', '513', '651', '1', '126'],
  ['04.jpg', '1366', '768', 'Car', '664', '827', '53', '293'],
  ['04.jpg', '1366', '768', 'Car', '994', '1320', '515', '768'],
  ['04.jpg', '1366', '768', 'Car', '1216', '1366', '297', '575'],
  ['04.jpg', '1366', '768', 'Car', '1095', '1260', '52', '193'],
  ['04.jpg', '1366', '768', 'Car', '320', '499', '1', '88'],
  ['04.jpg', '1366', '768', 'Car', '897', '1024', '3', '89']],
 [['06.jpg', '500', '500', 'Bycycle', '84', '230', '188', '426']],
 [['07.jpg', '1366', '768', 'Bycycle', '436', '724', '1', '211'],
  ['07.jpg', '1366', '768', 'Car', '165', '1065', '190', '615']],
 [['08.jpg', '1366', '768', 'SuperBike', '434', '901', '141', '579']],
 [['09.jpg', '4003', '2621', 'CruiserBike', '2001', '3464', '1148', '1902']],
 [['10.jpg', '3840', '2160', 'WineBottel', '1127', '1654', '91', '1933'],
  ['10.jpg', '3840', '2160', 'WineGlass', '1715', '2196', '637', '1929'],
  ['10.jpg', '3840', '2160', 'WineGlass', '2273', '2750', '660', '1937']],
 [['11.jpg', '5920', '3947', 'WineBottel', '5098', '5729', '923', '2673'],
  ['11.jpg', '5920', '3947', 'Graps', '10', '904', '2485', '3060'],
  ['11.jpg', '5920', '3947', 'Fruit', '73', '754', '3054', '3604'],
  ['11.jpg', '5920', '3947', 'Fruit', '710', '1266', '2823', '3554'],
  ['11.jpg', '5920', '3947', 'Fruit', '966', '1698', '2467', '3392'],
  ['11.jpg', '5920', '3947', 'Fruit', '698', '1654', '3660', '3867'],
  ['11.jpg', '5920', '3947', 'Bowl', '579', '1710', '3635', '3947'],
  ['11.jpg', '5920', '3947', 'WineGlass', '3166', '4041', '1592', '3704'],
  ['11.jpg', '5920', '3947', 'WineJar', '160', '3691', '642', '1954'],
  ['11.jpg', '5920', '3947', 'Graps', '4604', '5754', '2585', '3673'],
  ['11.jpg', '5920', '3947', 'WineCork', '4123', '4698', '3610', '3947']],
 [['12.jpg', '5327', '7990', 'Chair', '2601', '5088', '2845', '7370'],
  ['12.jpg', '5327', '7990', 'Plant&Gamla', '1163', '3013', '4657', '7395'],
  ['12.jpg', '5327', '7990', 'Plant&Gamla', '151', '1451', '3332', '5032'],
  ['12.jpg', '5327', '7990', 'Plant&Gamla', '88', '963', '5795', '6582'],
  ['12.jpg', '5327', '7990', 'Plant&Gamla', '51', '1063', '670', '2445'],
  ['12.jpg', '5327', '7990', 'Gamla', '13', '513', '4232', '5132'],
  ['12.jpg', '5327', '7990', 'Gamla', '651', '1251', '2945', '3457'],
  ['12.jpg', '5327', '7990', 'Gamla', '63', '538', '2895', '3420']],
 [['13.jpg', '3000', '2000', 'Chair', '1051', '1784', '981', '1878'],
  ['13.jpg', '3000', '2000', 'Chair', '1905', '2572', '987', '1829'],
  ['13.jpg', '3000', '2000', 'Chair', '2569', '2657', '948', '1590'],
  ['13.jpg', '3000', '2000', 'TVScreen', '796', '1232', '723', '1117'],
  ['13.jpg', '3000', '2000', 'Sofa', '5', '726', '960', '1314'],
  ['13.jpg', '3000', '2000', 'Frames', '32', '442', '414', '893'],
  ['13.jpg', '3000', '2000', 'NightLight', '590', '772', '705', '1099'],
  ['13.jpg', '3000', '2000', 'Jhumar', '402', '875', '329', '508'],
  ['13.jpg', '3000', '2000', 'light', '1505', '1917', '1', '254'],
  ['13.jpg', '3000', '2000', 'light', '1811', '2111', '129', '402'],
  ['13.jpg', '3000', '2000', 'Plant', '1754', '2032', '587', '966'],
  ['13.jpg', '3000', '2000', 'Bowl', '1429', '1596', '935', '984'],
  ['13.jpg', '3000', '2000', 'Bowl', '2081', '2190', '941', '984'],
  ['13.jpg', '3000', '2000', 'Dining', '1520', '2354', '996', '1063'],
  ['13.jpg', '3000', '2000', 'WoodenTabel', '584', '1151', '1129', '1526']],
 [['15.jpg', '1000', '667', 'Horse', '462', '684', '103', '560'],
  ['15.jpg', '1000', '667', 'Horse', '355', '458', '252', '447'],
  ['15.jpg', '1000', '667', 'Horse', '767', '861', '330', '488']],
 [['16.jpg', '4782', '3188', 'Horse', '781', '2356', '414', '3188'],
  ['16.jpg', '4782', '3188', 'Girl', '3016', '4271', '814', '3184'],
  ['16.jpg', '4782', '3188', 'Girl', '2271', '3221', '759', '3154']],
 [['17.jpg', '5040', '3360', 'Horse', '599', '1904', '84', '3360'],
  ['17.jpg', '5040', '3360', 'Horse', '3809', '5014', '311', '3348'],
  ['17.jpg', '5040', '3360', 'Boy', '1293', '3099', '490', '3332'],
  ['17.jpg', '5040', '3360', 'Girl', '2856', '4146', '669', '3326']],
 [['18.jpg', '4621', '3081', 'Horse', '2391', '3824', '874', '2907'],
  ['18.jpg', '4621', '3081', 'Car', '3681', '4210', '1554', '1788'],
  ['18.jpg', '4621', '3081', 'House', '3296', '4586', '964', '1659'],
  ['18.jpg', '4621', '3081', 'Girl', '1019', '1686', '912', '2754'],
  ['18.jpg', '4621', '3081', 'Girl', '1667', '2381', '1074', '2650'],
  ['18.jpg', '4621', '3081', 'Fansing', '10', '4615', '1554', '1802']],
 [['19.jpg', '4884', '3907', 'Boat', '1242', '2317', '2322', '3309'],
  ['19.jpg', '4884', '3907', 'Boat', '592', '1173', '2115', '2365'],
  ['19.jpg', '4884', '3907', 'Boat', '292', '736', '2053', '2165'],
  ['19.jpg', '4884', '3907', 'Boat', '4223', '4423', '2147', '2247'],
  ['19.jpg', '4884', '3907', 'Boat', '2880', '3192', '2122', '2228'],
  ['19.jpg', '4884', '3907', 'Boat', '2267', '2555', '2072', '2172'],
  ['19.jpg', '4884', '3907', 'Boat', '3261', '3505', '2109', '2184'],
  ['19.jpg', '4884', '3907', 'Boat', '1748', '2186', '2065', '2178'],
  ['19.jpg', '4884', '3907', 'Boat', '1205', '1423', '2059', '2134'],
  ['19.jpg', '4884', '3907', 'Boat', '3911', '4042', '2065', '2134'],
  ['19.jpg', '4884', '3907', 'Boat', '4630', '4884', '2109', '2203']],
 [['20.jpg', '3000', '2000', 'Boat', '1229', '1754', '1411', '1766']],
 [['21.jpg', '3861', '2574', 'Cow', '2274', '3054', '659', '2327'],
  ['21.jpg', '3861', '2574', 'Cow', '1078', '1490', '959', '1327'],
  ['21.jpg', '3861', '2574', 'Cow', '346', '846', '967', '1315']],
 [['23.jpg', '5765', '3844', 'Cow', '2506', '4947', '1998', '3656'],
  ['23.jpg', '5765', '3844', 'Cow', '1612', '2006', '2086', '2339'],
  ['23.jpg', '5765', '3844', 'Cow', '688', '906', '2045', '2186'],
  ['23.jpg', '5765', '3844', 'Cow', '2029', '2500', '2068', '2327'],
  ['23.jpg', '5765', '3844', 'Cow', '4900', '5088', '2127', '2274'],
  ['23.jpg', '5765', '3844', 'Cow', '5523', '5765', '2121', '2374'],
  ['23.jpg', '5765', '3844', 'Cow', '2617', '2988', '2098', '2245']],
 [['24.jpg', '1280', '781', 'Cat', '222', '752', '129', '779']],
 [['25.jpg', '1280', '1014', 'LittleBoy', '139', '525', '245', '1014'],
  ['25.jpg', '1280', '1014', 'Cat', '498', '685', '715', '977'],
  ['25.jpg', '1280', '1014', 'Dog', '719', '1112', '509', '962']],
 [['26.jpg', '1280', '720', 'Cat', '349', '594', '307', '659'],
  ['26.jpg', '1280', '720', 'Car', '13', '411', '275', '526'],
  ['26.jpg', '1280', '720', 'Girl', '694', '986', '29', '564']],
 [['27.jpg', '1280', '853', 'Dog', '233', '293', '584', '670'],
  ['27.jpg', '1280', '853', 'Dog', '695', '765', '539', '643'],
  ['27.jpg', '1280', '853', 'Human', '443', '609', '271', '665']],
 [['28.jpg', '1280', '851', 'Dog', '233', '439', '655', '821'],
  ['28.jpg', '1280', '851', 'Dog', '547', '702', '525', '673'],
  ['28.jpg', '1280', '851', 'Human', '415', '545', '300', '711']],
 [['29.jpg', '1280', '853', 'Dog', '246', '590', '297', '835'],
  ['29.jpg', '1280', '853', 'Woman', '581', '1280', '288', '848']],
 [['30.jpg', '1280', '710', 'Bird', '162', '867', '48', '547']],
 [['31.jpg', '1280', '850', 'Bird', '126', '367', '53', '290'],
  ['31.jpg', '1280', '850', 'Bird', '294', '419', '247', '400'],
  ['31.jpg', '1280', '850', 'Bird', '321', '554', '395', '596'],
  ['31.jpg', '1280', '850', 'Bird', '446', '600', '589', '746'],
  ['31.jpg', '1280', '850', 'Bird', '512', '846', '598', '829'],
  ['31.jpg', '1280', '850', 'Bird', '568', '851', '116', '492'],
  ['31.jpg', '1280', '850', 'Bird', '777', '1003', '1', '194'],
  ['31.jpg', '1280', '850', 'Bird', '863', '1181', '212', '386'],
  ['31.jpg', '1280', '850', 'Bird', '956', '1224', '400', '663']],
 [['32.jpg', '1280', '853', 'Bird', '112', '365', '182', '374'],
  ['32.jpg', '1280', '853', 'Bird', '596', '832', '144', '291'],
  ['32.jpg', '1280', '853', 'Bird', '378', '616', '386', '532'],
  ['32.jpg', '1280', '853', 'Bird', '652', '899', '545', '723'],
  ['32.jpg', '1280', '853', 'Bird', '920', '1116', '521', '660']],
 [['33.jpg', '1280', '720', 'AiroPlane', '184', '1004', '221', '458']],
 [['34.jpg', '1280', '720', 'AiroPlane', '12', '1134', '156', '556']],
 [['35.jpg', '1280', '788', 'Train', '486', '1057', '452', '668']],
 [['36.jpg', '1280', '853', 'Train', '330', '642', '362', '587']],
 [['37.jpg', '1280', '853', 'Train', '535', '702', '306', '519']],
 [['38.jpg', '1280', '960', 'Bus', '730', '1238', '359', '864'],
  ['38.jpg', '1280', '960', 'Car', '648', '726', '680', '753']],
 [['40.jpg', '1280', '853', 'Bus', '299', '598', '470', '696'],
  ['40.jpg', '1280', '853', 'Car', '207', '294', '584', '690'],
  ['40.jpg', '1280', '853', 'Bus', '629', '685', '569', '625']],
 [['41.jpg', '1280', '853', 'Bus', '108', '400', '587', '788'],
  ['41.jpg', '1280', '853', 'Bus', '376', '938', '526', '823'],
  ['41.jpg', '1280', '853', 'Bus', '1099', '1280', '627', '827'],
  ['41.jpg', '1280', '853', 'Car', '73', '117', '702', '758'],
  ['41.jpg', '1280', '853', 'Car', '1', '33', '709', '753']],
 [['07.jpg', '1366', '768', 'Bycycle', '428', '706', '1', '218'],
  ['07.jpg', '1366', '768', 'Car', '160', '1073', '218', '618']],
 [['08.jpg', '1366', '768', 'SuperBike', '435', '898', '141', '579']],
 [['09.jpg', '4003', '2621', 'CruiserBike', '2010', '3464', '1164', '1960']]]

In [127]:
#lets reduce the dimension 3D to 2D with the help of lambada function x and y  
data = reduce(lambda x, y : x+y, parser_all)

In [128]:
data

[['00.jpg', '5016', '2822', 'Car', '234', '1923', '1384', '1863'],
 ['00.jpg', '5016', '2822', 'Car', '1650', '3076', '1289', '1794'],
 ['00.jpg', '5016', '2822', 'Car', '3025', '4593', '977', '2089'],
 ['01.jpg', '1366', '768', 'Car', '28', '531', '551', '768'],
 ['01.jpg', '1366', '768', 'Car', '545', '905', '515', '667'],
 ['01.jpg', '1366', '768', 'Car', '961', '1247', '498', '604'],
 ['01.jpg', '1366', '768', 'Car', '1010', '1335', '612', '767'],
 ['02.jpg', '4128', '3096', 'Car', '1797', '2693', '2214', '2704'],
 ['02.jpg', '4128', '3096', 'Car', '497', '1188', '2076', '2481'],
 ['02.jpg', '4128', '3096', 'Car', '893', '1559', '1914', '2266'],
 ['02.jpg', '4128', '3096', 'Car', '183', '712', '1733', '1990'],
 ['02.jpg', '4128', '3096', 'Car', '245', '707', '1609', '1800'],
 ['02.jpg', '4128', '3096', 'Car', '1116', '1778', '1557', '1852'],
 ['02.jpg', '4128', '3096', 'Car', '1816', '2464', '1595', '1833'],
 ['02.jpg', '4128', '3096', 'Car', '873', '2012', '2757', '3096'],
 ['02.jpg', '4128', '3096', 'Car', '2126', '2926', '1871', '2257'],
 ['02.jpg', '4128', '3096', 'Car', '2940', '3893', '2057', '2504'],
 ['02.jpg', '4128', '3096', 'Car', '16', '402', '1438', '1604'],
 ['02.jpg', '4128', '3096', 'Car', '793', '1278', '1328', '1533'],
 ['02.jpg', '4128', '3096', 'Car', '1426', '1821', '1233', '1447'],
 ['02.jpg', '4128', '3096', 'Car', '2212', '2493', '1347', '1528'],
 ['02.jpg', '4128', '3096', 'Car', '2526', '2826', '1342', '1581'],
 ['02.jpg', '4128', '3096', 'Car', '2673', '2950', '1504', '1738'],
 ['02.jpg', '4128', '3096', 'Car', '2578', '2845', '1190', '1352'],
 ['02.jpg', '4128', '3096', 'Car', '935', '1259', '1209', '1333'],
 ['02.jpg', '4128', '3096', 'Car', '2731', '2916', '1114', '1242'],
 ['02.jpg', '4128', '3096', 'Car', '3273', '3754', '1566', '1861'],
 ['03.jpg', '5088', '3253', 'Taxi', '1649', '2091', '2479', '2910'],
 ['03.jpg', '5088', '3253', 'Taxi', '2038', '2301', '2584', '2837'],
 ['03.jpg', '5088', '3253', 'Taxi', '2291', '2565', '2516', '2826'],
 ['03.jpg', '5088', '3253', 'Car', '2695', '2897', '2565', '2753'],
 ['03.jpg', '5088', '3253', 'Ambulance', '2882', '3057', '2510', '2710'],
 ['03.jpg', '5088', '3253', 'Bus', '2679', '2766', '2449', '2500'],
 ['03.jpg', '5088', '3253', 'Car', '3659', '4114', '2504', '2929'],
 ['04.jpg', '1366', '768', 'Car', '631', '879', '392', '723'],
 ['04.jpg', '1366', '768', 'Car', '339', '573', '294', '541'],
 ['04.jpg', '1366', '768', 'Car', '113', '345', '212', '398'],
 ['04.jpg', '1366', '768', 'Car', '1', '306', '364', '757'],
 ['04.jpg', '1366', '768', 'Car', '177', '477', '600', '768'],
 ['04.jpg', '1366', '768', 'Car', '939', '1177', '270', '503'],
 ['04.jpg', '1366', '768', 'Car', '432', '603', '122', '283'],
 ['04.jpg', '1366', '768', 'Car', '234', '424', '62', '233'],
 ['04.jpg', '1366', '768', 'Car', '913', '1080', '93', '244'],
 ['04.jpg', '1366', '768', 'Car', '513', '651', '1', '126'],
 ['04.jpg', '1366', '768', 'Car', '664', '827', '53', '293'],
 ['04.jpg', '1366', '768', 'Car', '994', '1320', '515', '768'],
 ['04.jpg', '1366', '768', 'Car', '1216', '1366', '297', '575'],
 ['04.jpg', '1366', '768', 'Car', '1095', '1260', '52', '193'],
 ['04.jpg', '1366', '768', 'Car', '320', '499', '1', '88'],
 ['04.jpg', '1366', '768', 'Car', '897', '1024', '3', '89'],
 ['06.jpg', '500', '500', 'Bycycle', '84', '230', '188', '426'],
 ['07.jpg', '1366', '768', 'Bycycle', '436', '724', '1', '211'],
 ['07.jpg', '1366', '768', 'Car', '165', '1065', '190', '615'],
 ['08.jpg', '1366', '768', 'SuperBike', '434', '901', '141', '579'],
 ['09.jpg', '4003', '2621', 'CruiserBike', '2001', '3464', '1148', '1902'],
 ['10.jpg', '3840', '2160', 'WineBottel', '1127', '1654', '91', '1933'],
 ['10.jpg', '3840', '2160', 'WineGlass', '1715', '2196', '637', '1929'],
 ['10.jpg', '3840', '2160', 'WineGlass', '2273', '2750', '660', '1937'],
 ['11.jpg', '5920', '3947', 'WineBottel', '5098', '5729', '923', '2673'],
 ['11.jpg', '5920', '3947', 'Graps', '10', '904', '2485', '3060'],
 ['11.jpg', '5920', '3947', 'Fruit', '73', '754', '3054', '3604'],
 ['11.jpg', '5920', '3947', 'Fruit', '710', '1266', '2823', '3554'],
 ['11.jpg', '5920', '3947', 'Fruit', '966', '1698', '2467', '3392'],
 ['11.jpg', '5920', '3947', 'Fruit', '698', '1654', '3660', '3867'],
 ['11.jpg', '5920', '3947', 'Bowl', '579', '1710', '3635', '3947'],
 ['11.jpg', '5920', '3947', 'WineGlass', '3166', '4041', '1592', '3704'],
 ['11.jpg', '5920', '3947', 'WineJar', '160', '3691', '642', '1954'],
 ['11.jpg', '5920', '3947', 'Graps', '4604', '5754', '2585', '3673'],
 ['11.jpg', '5920', '3947', 'WineCork', '4123', '4698', '3610', '3947'],
 ['12.jpg', '5327', '7990', 'Chair', '2601', '5088', '2845', '7370'],
 ['12.jpg', '5327', '7990', 'Plant&Gamla', '1163', '3013', '4657', '7395'],
 ['12.jpg', '5327', '7990', 'Plant&Gamla', '151', '1451', '3332', '5032'],
 ['12.jpg', '5327', '7990', 'Plant&Gamla', '88', '963', '5795', '6582'],
 ['12.jpg', '5327', '7990', 'Plant&Gamla', '51', '1063', '670', '2445'],
 ['12.jpg', '5327', '7990', 'Gamla', '13', '513', '4232', '5132'],
 ['12.jpg', '5327', '7990', 'Gamla', '651', '1251', '2945', '3457'],
 ['12.jpg', '5327', '7990', 'Gamla', '63', '538', '2895', '3420'],
 ['13.jpg', '3000', '2000', 'Chair', '1051', '1784', '981', '1878'],
 ['13.jpg', '3000', '2000', 'Chair', '1905', '2572', '987', '1829'],
 ['13.jpg', '3000', '2000', 'Chair', '2569', '2657', '948', '1590'],
 ['13.jpg', '3000', '2000', 'TVScreen', '796', '1232', '723', '1117'],
 ['13.jpg', '3000', '2000', 'Sofa', '5', '726', '960', '1314'],
 ['13.jpg', '3000', '2000', 'Frames', '32', '442', '414', '893'],
 ['13.jpg', '3000', '2000', 'NightLight', '590', '772', '705', '1099'],
 ['13.jpg', '3000', '2000', 'Jhumar', '402', '875', '329', '508'],
 ['13.jpg', '3000', '2000', 'light', '1505', '1917', '1', '254'],
 ['13.jpg', '3000', '2000', 'light', '1811', '2111', '129', '402'],
 ['13.jpg', '3000', '2000', 'Plant', '1754', '2032', '587', '966'],
 ['13.jpg', '3000', '2000', 'Bowl', '1429', '1596', '935', '984'],
 ['13.jpg', '3000', '2000', 'Bowl', '2081', '2190', '941', '984'],
 ['13.jpg', '3000', '2000', 'Dining', '1520', '2354', '996', '1063'],
 ['13.jpg', '3000', '2000', 'WoodenTabel', '584', '1151', '1129', '1526'],
 ['15.jpg', '1000', '667', 'Horse', '462', '684', '103', '560'],
 ['15.jpg', '1000', '667', 'Horse', '355', '458', '252', '447'],
 ['15.jpg', '1000', '667', 'Horse', '767', '861', '330', '488'],
 ['16.jpg', '4782', '3188', 'Horse', '781', '2356', '414', '3188'],
 ['16.jpg', '4782', '3188', 'Girl', '3016', '4271', '814', '3184'],
 ['16.jpg', '4782', '3188', 'Girl', '2271', '3221', '759', '3154'],
 ['17.jpg', '5040', '3360', 'Horse', '599', '1904', '84', '3360'],
 ['17.jpg', '5040', '3360', 'Horse', '3809', '5014', '311', '3348'],
 ['17.jpg', '5040', '3360', 'Boy', '1293', '3099', '490', '3332'],
 ['17.jpg', '5040', '3360', 'Girl', '2856', '4146', '669', '3326'],
 ['18.jpg', '4621', '3081', 'Horse', '2391', '3824', '874', '2907'],
 ['18.jpg', '4621', '3081', 'Car', '3681', '4210', '1554', '1788'],
 ['18.jpg', '4621', '3081', 'House', '3296', '4586', '964', '1659'],
 ['18.jpg', '4621', '3081', 'Girl', '1019', '1686', '912', '2754'],
 ['18.jpg', '4621', '3081', 'Girl', '1667', '2381', '1074', '2650'],
 ['18.jpg', '4621', '3081', 'Fansing', '10', '4615', '1554', '1802'],
 ['19.jpg', '4884', '3907', 'Boat', '1242', '2317', '2322', '3309'],
 ['19.jpg', '4884', '3907', 'Boat', '592', '1173', '2115', '2365'],
 ['19.jpg', '4884', '3907', 'Boat', '292', '736', '2053', '2165'],
 ['19.jpg', '4884', '3907', 'Boat', '4223', '4423', '2147', '2247'],
 ['19.jpg', '4884', '3907', 'Boat', '2880', '3192', '2122', '2228'],
 ['19.jpg', '4884', '3907', 'Boat', '2267', '2555', '2072', '2172'],
 ['19.jpg', '4884', '3907', 'Boat', '3261', '3505', '2109', '2184'],
 ['19.jpg', '4884', '3907', 'Boat', '1748', '2186', '2065', '2178'],
 ['19.jpg', '4884', '3907', 'Boat', '1205', '1423', '2059', '2134'],
 ['19.jpg', '4884', '3907', 'Boat', '3911', '4042', '2065', '2134'],
 ['19.jpg', '4884', '3907', 'Boat', '4630', '4884', '2109', '2203'],
 ['20.jpg', '3000', '2000', 'Boat', '1229', '1754', '1411', '1766'],
 ['21.jpg', '3861', '2574', 'Cow', '2274', '3054', '659', '2327'],
 ['21.jpg', '3861', '2574', 'Cow', '1078', '1490', '959', '1327'],
 ['21.jpg', '3861', '2574', 'Cow', '346', '846', '967', '1315'],
 ['23.jpg', '5765', '3844', 'Cow', '2506', '4947', '1998', '3656'],
 ['23.jpg', '5765', '3844', 'Cow', '1612', '2006', '2086', '2339'],
 ['23.jpg', '5765', '3844', 'Cow', '688', '906', '2045', '2186'],
 ['23.jpg', '5765', '3844', 'Cow', '2029', '2500', '2068', '2327'],
 ['23.jpg', '5765', '3844', 'Cow', '4900', '5088', '2127', '2274'],
 ['23.jpg', '5765', '3844', 'Cow', '5523', '5765', '2121', '2374'],
 ['23.jpg', '5765', '3844', 'Cow', '2617', '2988', '2098', '2245'],
 ['24.jpg', '1280', '781', 'Cat', '222', '752', '129', '779'],
 ['25.jpg', '1280', '1014', 'LittleBoy', '139', '525', '245', '1014'],
 ['25.jpg', '1280', '1014', 'Cat', '498', '685', '715', '977'],
 ['25.jpg', '1280', '1014', 'Dog', '719', '1112', '509', '962'],
 ['26.jpg', '1280', '720', 'Cat', '349', '594', '307', '659'],
 ['26.jpg', '1280', '720', 'Car', '13', '411', '275', '526'],
 ['26.jpg', '1280', '720', 'Girl', '694', '986', '29', '564'],
 ['27.jpg', '1280', '853', 'Dog', '233', '293', '584', '670'],
 ['27.jpg', '1280', '853', 'Dog', '695', '765', '539', '643'],
 ['27.jpg', '1280', '853', 'Human', '443', '609', '271', '665'],
 ['28.jpg', '1280', '851', 'Dog', '233', '439', '655', '821'],
 ['28.jpg', '1280', '851', 'Dog', '547', '702', '525', '673'],
 ['28.jpg', '1280', '851', 'Human', '415', '545', '300', '711'],
 ['29.jpg', '1280', '853', 'Dog', '246', '590', '297', '835'],
 ['29.jpg', '1280', '853', 'Woman', '581', '1280', '288', '848'],
 ['30.jpg', '1280', '710', 'Bird', '162', '867', '48', '547'],
 ['31.jpg', '1280', '850', 'Bird', '126', '367', '53', '290'],
 ['31.jpg', '1280', '850', 'Bird', '294', '419', '247', '400'],
 ['31.jpg', '1280', '850', 'Bird', '321', '554', '395', '596'],
 ['31.jpg', '1280', '850', 'Bird', '446', '600', '589', '746'],
 ['31.jpg', '1280', '850', 'Bird', '512', '846', '598', '829'],
 ['31.jpg', '1280', '850', 'Bird', '568', '851', '116', '492'],
 ['31.jpg', '1280', '850', 'Bird', '777', '1003', '1', '194'],
 ['31.jpg', '1280', '850', 'Bird', '863', '1181', '212', '386'],
 ['31.jpg', '1280', '850', 'Bird', '956', '1224', '400', '663'],
 ['32.jpg', '1280', '853', 'Bird', '112', '365', '182', '374'],
 ['32.jpg', '1280', '853', 'Bird', '596', '832', '144', '291'],
 ['32.jpg', '1280', '853', 'Bird', '378', '616', '386', '532'],
 ['32.jpg', '1280', '853', 'Bird', '652', '899', '545', '723'],
 ['32.jpg', '1280', '853', 'Bird', '920', '1116', '521', '660'],
 ['33.jpg', '1280', '720', 'AiroPlane', '184', '1004', '221', '458'],
 ['34.jpg', '1280', '720', 'AiroPlane', '12', '1134', '156', '556'],
 ['35.jpg', '1280', '788', 'Train', '486', '1057', '452', '668'],
 ['36.jpg', '1280', '853', 'Train', '330', '642', '362', '587'],
 ['37.jpg', '1280', '853', 'Train', '535', '702', '306', '519'],
 ['38.jpg', '1280', '960', 'Bus', '730', '1238', '359', '864'],
 ['38.jpg', '1280', '960', 'Car', '648', '726', '680', '753'],
 ['40.jpg', '1280', '853', 'Bus', '299', '598', '470', '696'],
 ['40.jpg', '1280', '853', 'Car', '207', '294', '584', '690'],
 ['40.jpg', '1280', '853', 'Bus', '629', '685', '569', '625'],
 ['41.jpg', '1280', '853', 'Bus', '108', '400', '587', '788'],
 ['41.jpg', '1280', '853', 'Bus', '376', '938', '526', '823'],
 ['41.jpg', '1280', '853', 'Bus', '1099', '1280', '627', '827'],
 ['41.jpg', '1280', '853', 'Car', '73', '117', '702', '758'],
 ['41.jpg', '1280', '853', 'Car', '1', '33', '709', '753'],
 ['07.jpg', '1366', '768', 'Bycycle', '428', '706', '1', '218'],
 ['07.jpg', '1366', '768', 'Car', '160', '1073', '218', '618'],
 ['08.jpg', '1366', '768', 'SuperBike', '435', '898', '141', '579'],
 ['09.jpg', '4003', '2621', 'CruiserBike', '2010', '3464', '1164', '1960']]

In [129]:
# convert the data into Dataframe
df = pd.DataFrame(data,columns = ['filename', 'width', 'height', 'objectname', 'xmin','xmax', 'ymin', 'ymax'])

In [130]:
df.head()

  filename width height objectname  xmin  xmax  ymin  ymax
0   00.jpg  5016   2822        Car   234  1923  1384  1863
1   00.jpg  5016   2822        Car  1650  3076  1289  1794
2   00.jpg  5016   2822        Car  3025  4593   977  2089
3   01.jpg  1366    768        Car    28   531   551   768
4   01.jpg  1366    768        Car   545   905   515   667

In [131]:
df.shape

(179, 8)

In [132]:
df['objectname'].value_counts()

objectname
Car            53
Bird           15
Boat           12
Cow            10
Bus             7
Horse           7
Dog             6
Girl            6
Chair           4
Fruit           4
Plant&Gamla     4
Cat             3
Taxi            3
Gamla           3
Train           3
Bowl            3
Bycycle         3
WineGlass       3
AiroPlane       2
Human           2
light           2
SuperBike       2
Graps           2
CruiserBike     2
WineBottel      2
WineCork        1
Fansing         1
Ambulance       1
Woman           1
LittleBoy       1
Boy             1
House           1
WineJar         1
WoodenTabel     1
Dining          1
Plant           1
Jhumar          1
Frames          1
Sofa            1
TVScreen        1
NightLight      1
Name: count, dtype: int64

# Prepairing label using Yolo Model

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179 entries, 0 to 178
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   filename    179 non-null    object
 1   width       179 non-null    object
 2   height      179 non-null    object
 3   objectname  179 non-null    object
 4   xmin        179 non-null    object
 5   xmax        179 non-null    object
 6   ymin        179 non-null    object
 7   ymax        179 non-null    object
dtypes: object(8)
memory usage: 11.3+ KB

In [134]:
#type conversion Object to int 
cols = ['width', 'height', 'xmin', 'xmax', 'ymin', 'ymax']
df[cols] = df[cols].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179 entries, 0 to 178
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   filename    179 non-null    object
 1   width       179 non-null    int32
 2   height      179 non-null    int32
 3   objectname  179 non-null    object
 4   xmin        179 non-null    int32
 5   xmax        179 non-null    int32
 6   ymin        179 non-null    int32
 7   ymax        179 non-null    int32
dtypes: int32(6), object(2)
memory usage: 7.1+ KB

In [135]:
#Lets Apply Yolo Formula 
# center_x center_y
df['center_x'] = ((df['xmax']+df['xmin'])/2)/df['width']
df['center_y'] = ((df['ymax']+df['ymin'])/2)/df['height']
# width and height 
df['w'] = (df['xmax']-df['xmin'])/df['width']
df['h'] = (df['ymax']-df['ymin'])/df['height']

In [136]:
df.head()

,filename,width,height,objectname,xmin,xmax,ymin,ymax,center_x,center_y,w,h
0,00.jpg,5016,2822,Car,234,1923,1384,1863,0.215012,0.575301,0.336722,0.169738
1,00.jpg,5016,2822,Car,1650,3076,1289,1794,0.471093,0.546244,0.284290,0.178951
2,00.jpg,5016,2822,Car,3025,4593,977,2089,0.759370,0.543232,0.312600,0.394047
3,01.jpg,1366,768,Car,28,531,551,768,0.204612,0.858724,0.368228,0.282552
4,01.jpg,1366,768,Car,545,905,515,667,0.530747,0.769531,0.263543,0.197917

# Split Data Into Train and test

In [137]:
images = df['filename'].unique()

In [138]:
len(images)

38

In [139]:
#80% train and 20% test 
img_df = pd.DataFrame(images, columns=['filename'])
#img_df.head()

img_train = tuple(img_df.sample(frac=0.8)['filename']) #shuffle and 80% of images

In [140]:
img_train

('33.jpg',
 '11.jpg',
 '24.jpg',
 '17.jpg',
 '18.jpg',
 '07.jpg',
 '29.jpg',
 '41.jpg',
 '19.jpg',
 '12.jpg',
 '08.jpg',
 '16.jpg',
 '06.jpg',
 '23.jpg',
 '40.jpg',
 '04.jpg',
 '01.jpg',
 '36.jpg',
 '38.jpg',
 '27.jpg',
 '32.jpg',
 '15.jpg',
 '21.jpg',
 '30.jpg',
 '25.jpg',
 '00.jpg',
 '03.jpg',
 '28.jpg',
 '31.jpg',
 '09.jpg')

In [141]:
img_test = tuple(img_df.query(f'filename not in {img_train}')['filename']) #shuffle and 20% of images

In [142]:
img_test

('02.jpg',
 '10.jpg',
 '13.jpg',
 '20.jpg',
 '26.jpg',
 '34.jpg',
 '35.jpg',
 '37.jpg')

In [143]:
len(img_train), len(img_test)

(30, 8)

In [144]:
train_df = df.query(f'filename in {img_train}')
test_df = df.query(f'filename in {img_test}')

In [145]:
train_df.all

<bound method DataFrame.all of     filename  width  height   objectname  xmin  xmax  ymin  ymax  center_x  \
0     00.jpg   5016    2822          Car   234  1923  1384  1863  0.215012
1     00.jpg   5016    2822          Car  1650  3076  1289  1794  0.471093
2     00.jpg   5016    2822          Car  3025  4593   977  2089  0.759370
3     01.jpg   1366     768          Car    28   531   551   768  0.204612
4     01.jpg   1366     768          Car   545   905   515   667  0.530747
..       ...    ...     ...          ...   ...   ...   ...   ...       ...
174   41.jpg   1280     853          Car     1    33   709   753  0.013281
175   07.jpg   1366     768      Bycycle   428   706     1   218  0.415081
176   07.jpg   1366     768          Car   160  1073   218   618  0.451318
177   08.jpg   1366     768    SuperBike   435   898   141   579  0.487921
178   09.jpg   4003    2621  CruiserBike  2010  3464  1164  1960  0.683737

     center_y         w         h
0    0.575301  0.336722  0.169738
1    0.546244  0.284290  0.178951
2    0.543232  0.312600  0.394047
3    0.858724  0.368228  0.282552
4    0.769531  0.263543  0.197917
..        ...       ...       ...
174  0.856975  0.025000  0.051583
175  0.142578  0.203514  0.282552
176  0.544271  0.668375  0.520833
177  0.468750  0.338946  0.570312
178  0.595956  0.363228  0.303701

[134 rows x 12 columns]>

In [146]:
test_df.head()

,filename,width,height,objectname,xmin,xmax,ymin,ymax,center_x,center_y,w,h
7,02.jpg,4128,3096,Car,1797,2693,2214,2704,0.543847,0.794251,0.217054,0.158269
8,02.jpg,4128,3096,Car,497,1188,2076,2481,0.204094,0.735950,0.167393,0.130814
9,02.jpg,4128,3096,Car,893,1559,1914,2266,0.296996,0.675065,0.161337,0.113695
10,02.jpg,4128,3096,Car,183,712,1733,1990,0.108406,0.601260,0.128149,0.083010
11,02.jpg,4128,3096,Car,245,707,1609,1800,0.115310,0.550549,0.111919,0.061693

# Assign id number to object names

In [147]:
#label encoding 
def label_encoding(x):
    labels = {'person': 0, 'Car':1, 'Taxi':2, 'Ambulance':3, 'Bus':4 , 'Bycycle':5,
        'SuperBike':6, 'CruiserBike':7, 'WineGlass':8, 'WineJar':9, 'WineBottel':10, 'Fruit':11, 
        'Graps':12, 'WineCork':13, 'Bowl':14, 'Chair':15, 'Plant&Gamla':16, 'Gamla':17, 'Plant':18, 
        'light':19, 'Dining':20, 'WoodenTabel':21, 'Frames':22, 'NightLight':23, 'TVScreen':24, 
        'Sofa':25, 'Jhumar':26, 'Horse':27, 'Girl':28, 'Boy':29, 'House':30, 'Fansing':31, 
        'Boat':32, 'Cow':33, 'Cat':34, 'Dog':35, 'LittleBoy':36, 'Dog':37, 'Bird':38, 'AiroPlane':39, 
        'Train':40, 'Human':41,'Woman':42}
    return labels[x]

In [150]:
train_df['id'] = train_df['objectname'].apply(label_encoding)
test_df['id'] = test_df['objectname'].apply(label_encoding)

KeyError: 'objectname'

In [149]:
train_df.head(10)

,filename,width,height,objectname,xmin,xmax,ymin,ymax,center_x,center_y,w,h,id
0,00.jpg,5016,2822,Car,234,1923,1384,1863,0.215012,0.575301,0.336722,0.169738,1
1,00.jpg,5016,2822,Car,1650,3076,1289,1794,0.471093,0.546244,0.284290,0.178951,1
2,00.jpg,5016,2822,Car,3025,4593,977,2089,0.759370,0.543232,0.312600,0.394047,1
3,01.jpg,1366,768,Car,28,531,551,768,0.204612,0.858724,0.368228,0.282552,1
4,01.jpg,1366,768,Car,545,905,515,667,0.530747,0.769531,0.263543,0.197917,1
5,01.jpg,1366,768,Car,961,1247,498,604,0.808199,0.717448,0.209370,0.138021,1
6,01.jpg,1366,768,Car,1010,1335,612,767,0.858346,0.897786,0.237921,0.201823,1
27,03.jpg,5088,3253,Taxi,1649,2091,2479,2910,0.367531,0.828312,0.086871,0.132493,2
28,03.jpg,5088,3253,Taxi,2038,2301,2584,2837,0.426395,0.833231,0.051690,0.077774,2
29,03.jpg,5088,3253,Taxi,2291,2565,2516,2826,0.477201,0.821088,0.053852,0.095297,2